name: Download and Push

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Download File
      run: |
        curl -o resolvers.txt https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add resolvers.txt
        git commit -m "Update resolvers.txt"
        git push
